#!/usr/bin/env bash

# either 'apt-fast' or 'apt-get'
# apt-fast has easy ppa installation on ubuntu.. 
package_mgr='apt-fast'

# Methods to get distribution information
getDistribution() {
	cat /etc/*-release | sed -e "s/=/ /g" | awk '$1=="DISTRIB_ID" {print $2};'
}

getRelease() {
	cat /etc/*-release | sed -e "s/=/ /g" | awk '$1=="DISTRIB_RELEASE" {print $2};'
}

# Install dependencies for add-apt-repository
sudo apt-get install -y python-software-properties software-properties-common

if [[ $package_mgr == 'apt-fast' && $(getDistribution) == 'Ubuntu' ]]; then
	echo 'Debian Package Manager Selected'
	echo 'PACKAGE MANAGER:' $package_mgr
	# Install apt-fast
	sudo add-apt-repository -y ppa:saiarcot895/myppa
	sudo apt-get update
	sudo apt-get -y install apt-fast
elif [[ $package_mgr == 'apt-get' ]]; then
	echo 'Debian Package Manager Selected'
	echo 'PACKAGE MANAGER:' $package_mgr
else
	echo 'Non-Debian Package Manager Selected'
	echo 'PACKAGE MANAGER:' $package_mgr
fi

# first upgrade repository cache 
sudo $package_mgr update
sudo $package_mgr -y upgrade

# install system essential packages
sudo $package_mgr -y build-dep build-essential

# install basic utilities
sudo $package_mgr -y install vim
sudo $package_mgr -y install ngrep
sudo $package_mgr -y install jq
sudo $packagem_gr -y install vlc
sudo $package_mgr -y install deluge
sudo $package_mgr -y install guake
sudo $package_mgr -y install curl
sudo $package_mgr -y install git
sudo $package_mgr -y install xclip
sudo $package_mgr -y install gpodder
sudo $package_mgr -y install fbreader
sudo $package_mgr -y install focuswriter
# install zram config
sudo $package_mgr -y install zram-config

# Optional Packages
# sudo $package_mgr -y install extremetuxracer
# sudo $package_mgr -y install wine
# sudo $package_mgr -y install dosbox

# go to homdir
cd ~/Chromebook-Automation

# install all shell installs
for file in ./shell-installers/*; do
    echo "Executing Shell Inst File: $file"
    $file
done

# Execute all app-installer scripts
for file in ./app-installers/*; do
    echo "Executing App Inst File: $file"
    $file
done

# Install compton
./compton/install-compton

# Copy bin utils to local bin
sudo cp ./local-bin-utils/* /usr/local/bin/

echo "And the final PWD is:" $(pwd)

# Install recent generic linux kernel for trusty
# sudo apt-get install linux-image-generic-lts-trusty
# Install AUFS support
# sudo apt-get -y install linux-image-virtual && sudo apt-get -y install linux-image-extra-virtual

