#!/bin/bash

if [[ ! -e /usr/bin/brackets ]]; then
	echo 'Installing Brackets editor...'
	sudo add-apt-repository -y ppa:webupd8team/brackets
	sudo apt-get update
	sudo apt-get install -y brackets
else
	echo 'Brackets editor already installed!'
fi
