#!/bin/bash
# install btsync
#***You will have to add the run-btsync executable to startup programs
if [ ! -e ~/btsyncf ]; then
    curl -LO https://download-cdn.getsyncapp.com/stable/linux-x64/BitTorrent-Sync_x64.tar.gz
    mkdir ~/btsyncf
    tar -xzf *Sync*.tar.gz -C ~/btsyncf
    rm *Sync*.tar.gz
fi

# download personal media server, and install movet utility
../movet-inst