#!/bin/bash
# install chrome
if [ ! -e /usr/bin/google-chrome ]; then
    sudo apt-get -y install libxss1 libappindicator1 libindicator7
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    sudo dpkg -i google-chrome*.deb
    sudo apt-get -yf install
    sudo rm *google-chrome*.deb*
fi